theme: jekyll-theme-minimal
minima:
  skin: dark

title: API Documentation
logo: /assets/img/logo.png
description: A detailed guide and reference to API for Dementia and MCI Detection
url: "https://spectruminsights.github.io/API-Documentation"

markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
