theme: jekyll-theme-minimal

title: API Documentation for Dementia and MCI Detection
description: A detailed guide and reference to API
url: "https://spectruminsights.github.io/API-Documentation"

markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
